import os

rule get_data:
    output:
        "data/costs_2030.csv",
        "data/time-series-lecture-2.csv"
    shell: "python scripts/get_data.py"

rule get_costs:
    input: "data/costs_2030.csv"
    output: "data/costs.csv"
    shell: "python scripts/get_costs.py"

rule get_timeseries:
    input: "data/time-series-lecture-2.csv"
    output: "data/timeseries.csv"
    # Using script, the Python module is imported into the same
    # namespace as Snakemake see https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#external-scripts
    script: "scripts/get_timeseries.py"

rule build_model:
    input:
        ts=rules.get_timeseries.output,
        costs=rules.get_costs.output
    output:
        "results/cem.nc"
    shell: "python scripts/build_model.py"

rule add_constraint:
    input:
        rules.build_model.output
    output:
        "results/cem_{CO2}.nc"
    # ``run:`` places the code directly into the Snakefile.  Careful!
    run:
        import pypsa
        network = pypsa.Network(str(input[0]))
        network.global_constraints.loc["CO2Limit", "constant"] = float(wildcards.CO2) * 1e6
        network.export_to_netcdf(str(output[0]))

rule solve:
    input:
        rules.add_constraint.output
    output:
        "results/solved_cem_{CO2}.nc"
    shell: "python scripts/solve.py {input} {output}"

rule aggregation:
    input:
        ["results/solved_cem_{emission}.nc".format(emission=emission) for emission in [150, 100, 50, 25, 0]]
    output:
        "results/statistics.csv"
    # This code should really be placed into a module rather than embedded in the snakefile.
    # Note how the ``run:`` command doesn't require quotation marks. Wildcards are accessed directly without
    # curly brackets `{}`
    # The code is run here in the Snakefile.
    run:
        import pypsa
        import pandas as pd
        sensitivity = {}
        for network_path in input:
            n = pypsa.Network(network_path)
             # Hacky line which extract the CO2 emission.
            emissions = n.global_constraints.loc["CO2Limit", "constant"] / 1e6
             # This could be avoided by adding a separate rule to extract statistics from each model run before an aggregation step
            sensitivity[str(emissions)] = (pd.concat([n.statistics.capex(), n.statistics.opex()])
            .groupby("carrier")
            .sum()
            .div(1e9))
        df = pd.DataFrame(sensitivity).T
        df.to_csv(str(output))

rule plot:
    input: rules.solve.output
    output: "results/figure_{CO2}.png"
    shell: "python scripts/plot.py {input} {output}"

rule all:
    input:
        plots = expand("results/figure_{CO2}.png", CO2=[150, 100, 50, 25, 0]),
        stats = rules.aggregation.output
